### ISSUE TITLE
Virtual machines are powered on before disks attachments

### ISSUE THREAD

**Issue by roct37** [Cloud-Temple/terraform-provider-cloudtemple#114]
Hello,

When we provision a VM with terraform and add other disks, the VM boots before creating and attaching the disks.

So, the vm requires bus scans or reboot to detect the added disks.

Can the virtual machine be started after the disks are created ?

**Comment by pbesret** [comment]
Hello, this is a known issue but is the normal behavior of Terraform since resources are created with dependencies to each other.

The virtual disk needs a VM to be created and we cannot power on the VM in the creation process of the virtual disk.
One solution could be to create the virtual disks in the virtual machine process but we cannot do this at this moment.

Will look for a solution later.

Thanks for understanding.
Paul

**Comment by pbesret** [comment]
Related to #139
